# 中国的包容性财政体制——基于非规范性收入的考察 - 

## 作者

吕炜

* 东北财经大学党委副书记、校长
* 经济学博士

王伟同

* 东北财经大学经济与社会发展研究院副院长

## 概念

非规范性收入：游离于预算之外的预算外收入和制度外收入

> 基本上是各种各样、形形色色的政府收费——高培勇
>
> 企业留利、行政收费、土地出让、地方债等多种形式

## 摘要

问题：如何解释「地方财政的非规范行为」与「中央和地方激励相容」之间的逻辑悖论

抓手：基于「地方自主财力长期依赖非规范性财政收入」的事实

解释方法：一个包含「中央和地方」双重行为视角的「包容性财政体制」分析框架

解决问题：

1. 可以阐释「改革进程中长期存在的以非规范性收入为载体的隐形分权合约」
2. 刻画在「中央财政容忍」和「地方财政自主的行为动机」下中央和地方「财政互动」的制度空间和动态过程
3. 阐明「非规范性收入」、「中央和地方激励相容」与「经济增长及市场化改革」之间的逻辑一致性

解释路径：在包容性财政体制分析框架下，普遍内生于中国工业化和城市化进程中的非规范性收入，不仅

1. 弥补了正式预算制度下地方事权、支出责任与财力间的不适应
2. 而且在保障制度平稳运行的同时实现了「地方行为」与「经济增长目标」的激励相容

包容性财政体制分析框架，兼顾了地方活力与中央驾驭能力，是中国能够兼顾经济快速增长和市场化改革双重目标的重要制度逻辑。

## 引言

改革开放成就——主流认识：地方发展经济的积极性被有效激发

* 地方动机
  * 财政分权的经济激励
  * 政治晋升的政治激励

地方政府的积极性源自中央层面的制度安排，地方和中央的两个积极性共存

> 中央和地方两个积极性本质上是一个有机的整体，地方积极性的调动离不开中央积极性的发挥

问题：什么样的制度设计和体制安排有效支撑了「中央」和「地方」两个积极性的持续有效发挥，进而形成了兼顾中央统筹驾驭与地方活力激发的中国发展模式？

本文关切：实现中央和地方关系中激励相容的动态过程的制度条件

1. 中央政府赋予了地方政府什么样的**手段和权力**来实现其发展的积极性，并且这种方式能够在改革过程的不同阶段得到一致性的解释，特别是关于1 9 9 4年分税制前后的重大体制性变化的解释

   > 显然已有的基于分权合约稳定性前提下的财政分权理论难以对此给出一致的解释

2. 转轨体制下的动态过程中，中央政府在一个改革的长过程中如何通过**赋权与纠偏的制度设计**，确保地方政府的竞争不偏离总体改革目标并带来一个好的制度的渐进实现。

研究对象：中央和地方财政关系中的动态过程

> 中央和地方财政关系在中央和地方两个积极性的发挥上具有决定性作用,是理解中央和地方激励相容过程与中国经济发展奇迹的关键

经验抓手：改革开放以来...「非规范性收入问题」以及「中央和地方体制的频繁变动」而常常为人所诟病

理论提出：包容性财政体制

> 中央政府会对地方政府非规范性收入给予**有条件容忍,**地方政府会追逐以非规范性收入为代表的**自主可控财力**,这种中央和地方行为逻辑可能是中国财政分权体制的真正内核。

> 中央政府会**审慎把握**非规范性收入扩张所带来的负面风险和影响,逐步对其进行规范或取缔,保障地方行为激励相容于中央改革目标。
>
> 相较于预算内收入的正式制度调整而言,非规范性收入具有较强的**制度弹性**,有助于更加灵活地调适地方事权与支出责任之间的矛盾,为中央和地方在财政体制设计上提供正式制度之外的弹性空间,也为改革进程提供试错和容错的制度缓冲。

## 包容性财政体制的内涵

### 现有理论的不足

#### **现有理论**

1. 财政分权理论解释了地方政府为增长而竞争的动机
   1. 存在争议：分权可能不会促进经济增长，反而滋生腐败、市场分割、重复建设
2. 政治晋升理论解释了官员的个体动机和行为

#### 不足

1. 中国真正且持续稳定的财政分权来自预算制度之外，而非预算制度内的分权。
   * 地方无法掌握预算内支出的用途，甚至需要另寻资金来弥补公共领域的支出缺口
2. 规范的财政分权理论要求财政体制存在 “ **有效承诺效应**” ,但中国的中央和地方财政体制并不稳定。
3. 中央政府始终是中央和地方互动过程中的重要一方,而财政分权和政治晋升理论忽视了中央政府的作用或者将其视作外生变量

### 包容性财政体制的基本内涵

包容性财政体制

* 一种建构于正式中央和地方财政制度之上的**非正式**财政制度安排
* 包容性财政体制可以定义为能够**有效调动地方积极性**、**更好贯彻落实中央战略意图**的富有**灵活性**的财政体制。
* 以**非规范性收入**为载体，以**中央财政容忍**和**地方财力自主**为行为逻辑
* 构建了有利于实现中央和地方激励相容的**弹性制度空间**，形成了兼顾中央统筹驾驭和地方活力激发的中央和地方财政制度安排。

#### 包容性财政体制与中央和地方政府行为动机

地方政府：收入不足

> 地方政府在满足下放的公共事权与以经济绩效为考核标准的政治激励的双重压力下,对自主财力的支出需求开始大幅扩张,正式财政分权制度下始终难以满足地方支出需要,导致了地方事权、支出责任与财力的长期不匹配,也由此引出了地方政府通过非规范性财政行为的方式获取财政资金以满足支出需要的局面。

中央政府：容忍竞争

> 为有效激励地方政府发展经济，通过容忍地方政府的非规范性财政行为，为地方政府的财政活动提供了正式预算制度以外的自主财政空间

在包容性财政体制下，地方政府开展竞争的重要领域是正式预算制度外的非规范性收入。

#### 包容性财政体制的运行逻辑

提供了以非规范性收入为载体的**弹性制度空间**，让地方政府竞争得以持续开展。

中央政府通过对非规范性财政行为**容忍边界的掌控**， 兼顾了地方活力与中央驾驭能力

* 地方缺乏抵御改革的正当理由

非规范性收入会**根据特定市场化阶段而呈现不同形态**，这其中蕴含了中央对地方赋权与纠偏的互动过程

> 只要中国**市场化改革进程没有完成**，仍存在着计划领域要素的市场化需求,即地方政府还可以开拓出新的自主财力实现方式，这种中央和地方财政互动关系就有其存在的合理性和必要性，也构成了中国市场化改革进程中中央和地方政府行为逻辑的核心支配力量。

## 包容性财政体制下分规范性收入的演进逻辑

### 让利与纠偏：财政包干制下地方企业留利的央地互动

财政包干制：中央对各省级财政单位的财政收支进行包干，地方增收的部分按一定比例留下自用，多收多支、少收少支，自求平衡

#### 藏富于企：乡镇企业兴起

逆向软预算约束，周雪光

问题：

1. 地方政府有意识地封锁地区市场、保护本地企业
2. 中央财政出现困难，不得不向地方讨要以维持运转

#### 规范企业留利：中央政府的困境与纠偏

分税制改革

### 行政与市场：分税制后地方获取自主财力的两种方式

1. 行政事业性收费的增长与消减

   > 地方政府通过行政收费获取自主财力的方式,由于无法兼容经济增长的目标, 同时严重侵蚀了正式预算制度的运行,因此是一种无法内生于经济增长模式的非规范性收入形式。

2. 土地财政

非规范性收入获取途径的转变

> 虽然每一阶段的非规范性收入都存在或多或少的**不合理或不规范**性,但事实上无论是企业留利、行政事业收费还是土地财政,都客观适应了当时的改革发展环境，在当时历史条件下为调动地方发展积极性注入了动力，并为改革发展提供了有效的财力保障。**尽管中央政府会及时对存在的问题进行纠偏，但允许地方政府探索自主财力的制度空间从来没有被彻底关闭。**中央始终赋予了地方政府极大的经济自主权利，地方政府仍然可以继续寻找新制度环境下的自主财力增长模式。

### 债务与风险：地方自主财力债务化背景下中央和地方的互动

早期：市场规模小、政府资源有限——风险小

当下

> 随着市场化改革的深入尤其是**资本市场和金融市场的发展**，政府手中的资源能够参与市场交换的部分越来越多，地方政府在寻求自主财力的体制激励下，开始探索**将政府资源与资本市场相结合**的方式获取自主财力。这种**通过资本市场融资方式获取的自主财力，放大并提前变现了地方政府现时收益，更大限度地助力了地方政府的发展激励，但同时也急剧放大了包容性财政体制运行的成本和风险**

## 包容性财政体制的制度根源

央地权责失衡

内生于中国经济转轨过程

* 支出责任的不断下沉与权责划分的不明确
* 地方政府被赋予了**发展经济的职能**，也成为地方政府重要的事权与支出责任，使得地方对自主财力产生了几乎无限的需求

## 结论与展望

政策含义

1. 权责统一
2. 保留包容性财政体制
3. 将地方自主财力逐步纳入正式财政制度
4. 构建稳定的地方税种

## 评论

「财政联邦主义」+「一统体制与有效治理」的结合。对「非规范性收入」和「包容性财政体制」的分析似乎没有跳出钱和周的框架。当然，将两者的逻辑进行整合是有价值的。

「包容性」似乎在强调「地方自主」和「中央纠偏」的动态过程。但在中央智库水平提高（90年后）、法治建设逐步完善、经济发展蓝图日益清晰的情况下，以土地财政为代表的「非规范性收入」究竟是「地方自主」的，还是「受中央领导的」，可能还需要讨论。如果是受中央领导的，「包容性」的概念是否能站住脚？「一统体制与有效治理」、「常规与运动」、「治理转轨」这些概念是否更好用？

作者对「包容性」概念的历史考察着眼于「非规范性收入」。事实上，地方「预算外支出」可能更加多样。

